# Generated by Django 3.2.2 on 2021-06-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='question8',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='question9',
            field=models.IntegerField(default=1),
        ),
    ]
