# Generated by Django 3.2.2 on 2021-06-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210601_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='question8',
            field=models.CharField(default='', max_length=30),
        ),
    ]
