# Generated by Django 3.2.2 on 2021-06-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_quizz_question8'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='question10',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='question8',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='question9',
            field=models.IntegerField(default=0),
        ),
    ]
