# Generated by Django 3.2.2 on 2021-06-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210601_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='result_question1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizz',
            name='result_question10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizz',
            name='result_question2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizz',
            name='result_question3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizz',
            name='result_question4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizz',
            name='result_question5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizz',
            name='result_question6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizz',
            name='result_question7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizz',
            name='result_question8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizz',
            name='result_question9',
            field=models.IntegerField(default=0),
        ),
    ]
