# Generated by Django 3.2.2 on 2021-06-01 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20210601_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizz',
            name='question1',
        ),
        migrations.RemoveField(
            model_name='quizz',
            name='question10',
        ),
        migrations.RemoveField(
            model_name='quizz',
            name='question2',
        ),
        migrations.RemoveField(
            model_name='quizz',
            name='question3',
        ),
        migrations.RemoveField(
            model_name='quizz',
            name='question4',
        ),
        migrations.RemoveField(
            model_name='quizz',
            name='question5',
        ),
        migrations.RemoveField(
            model_name='quizz',
            name='question6',
        ),
        migrations.RemoveField(
            model_name='quizz',
            name='question7',
        ),
        migrations.RemoveField(
            model_name='quizz',
            name='question8',
        ),
        migrations.RemoveField(
            model_name='quizz',
            name='question9',
        ),
        migrations.RemoveField(
            model_name='quizz',
            name='result_question1',
        ),
        migrations.RemoveField(
            model_name='quizz',
            name='result_question10',
        ),
        migrations.RemoveField(
            model_name='quizz',
            name='result_question2',
        ),
        migrations.RemoveField(
            model_name='quizz',
            name='result_question3',
        ),
        migrations.RemoveField(
            model_name='quizz',
            name='result_question4',
        ),
        migrations.RemoveField(
            model_name='quizz',
            name='result_question5',
        ),
        migrations.RemoveField(
            model_name='quizz',
            name='result_question6',
        ),
        migrations.RemoveField(
            model_name='quizz',
            name='result_question7',
        ),
        migrations.RemoveField(
            model_name='quizz',
            name='result_question8',
        ),
        migrations.RemoveField(
            model_name='quizz',
            name='result_question9',
        ),
    ]
