# Generated by Django 3.2.2 on 2021-06-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210601_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result_Quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_question1', models.IntegerField(default=0)),
                ('result_question2', models.IntegerField(default=0)),
                ('result_question3', models.IntegerField(default=0)),
                ('result_question4', models.IntegerField(default=0)),
                ('result_question5', models.IntegerField(default=0)),
                ('result_question6', models.IntegerField(default=0)),
                ('result_question7', models.IntegerField(default=0)),
                ('result_question8', models.IntegerField(default=0)),
                ('result_question9', models.IntegerField(default=0)),
                ('result_question10', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='quizz',
            name='question1',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='quizz',
            name='question10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizz',
            name='question2',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='quizz',
            name='question3',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=30),
        ),
        migrations.AddField(
            model_name='quizz',
            name='question4',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='quizz',
            name='question5',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='quizz',
            name='question6',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=30),
        ),
        migrations.AddField(
            model_name='quizz',
            name='question7',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='quizz',
            name='question8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizz',
            name='question9',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='question1',
            field=models.CharField(default='', max_length=10),
        ),
    ]
